- usernames.md
For Fork tutorial username collection
> mackeycalvin_forktutorial

- usernames.md
I added my username to usernames.md
- Marina Becker
> Pull Request

- usernames.md
Adding my username. Sort of accidentally left newline after name, shouldn't interfere with next merges though.
> adding username for Patrick Mahle

- usernames.md
Includes name, username, and email.
> Added my info

- usernames.md
Adding my Information to the usernames.md , Eric Wetzel
> Eric Wetzel's information

- usernames.md
Username: ehsung
Name: Edward Sung
> Username Updated for Edward Sung

- usernames.md
> Cjho3 changes

- usernames.md
> Added info

- usernames.md
> Added username

- 2016_roster.csv
> Diane Nguyen username:xdiane

- 2016_roster.csv
> Miranda added username

- 2016_roster.csv
> uploading my sassy github username to this repository

- 2016_roster.csv
> name added

- 2016_roster.csv
added my username to the roster. no other changes.
> Added my username -Jacob North

- 2016_roster.csv
> 2016_roster.csv

- 2017_Roster.csv
added my info, and I guess because I used vim a newline...
> added gina turco information

- 2017_Roster.csv
> Added Imran's username

- 2017_Roster.csv
> github username added

- 2017_Roster.csv
Hi this is Koki I added my user name.
> user name added

- 2018_Roster.csv
> I finally.. pushed it =')

- 2018_Roster.csv
I hope  this is going to be useful one day
> I love this class

- 2018_Roster.csv
> added my git user to file

- 2019_Roster.csv
added my username next to my name on the roster.
> added Ria Marathe's username

- 2019_Roster.csv
> Added github Username

- 2019_Roster.csv
> add username

- 2019_Roster.csv
> added github user name

- 2019_Roster.csv
> Hongtao_UsernameAdded

- 2019_Roster.csv
added my github user name after the last comma on the file "2019_Roster.csv"
> added github user name dlhan1022

- 2019_Roster.csv
Added username for Elizabeth Roberts to roster
> add username to roster

- 2019_Roster.csv
> add-username

- 2019_Roster.csv
> added user to assignment 1

- 2019_Roster.csv
> added my username

- 2019_Roster.csv
I added my GitHub username "ccheng" to the roster.
> 2019_Roster.csv

- 2019_Roster.csv
Reverts UCDBIS180L/gh-usernames#194
> Revert "Update 2019_Roster.csv"

- 2019_Roster.csv
> 2019_Roster

- 2019_Roster.csv
I'm so sorry this is so late. I only realised today that I didn't successfully add my username to the roster.
> adding gnrobinson username - sorry

- 2020_Roster.csv
> Add my github username to github

- 2020_Roster.csv
added github username for Kevin Lee
> Add Kevin Lee github username

- 2020_Roster.csv
> Betsy_added

- 2020_Roster.csv
> Added Stratton's username

- 2020_Roster.csv
This is the pull request to add my git-hub username to your file.
> I added my git-hub username

- 2020_Roster.csv
I added my GitHub username to my line in 2020_Roster.csv.
> Added username for Lisa Malins

- 2020_Roster.csv
>  updated 2020_Roster.csv

- 2020_Roster.csv
> KellyChau'sUpdate 2020_Roster.csv

- 2020_Roster.csv
Please add Izzie's github username. I hope this worked correctly. Sorry I'm slow to figure this out. Thank you.
> Add Izzie username

- 2020_Roster.csv
I'm sorry if I'm doing this wrong, this is still taking me time to get used to.
> Samuel Ng Github Username

- 2020_Roster.csv
> Added Zhenzhi Wang's username

- 2020_Roster.csv
####Jerry
* Add Jerry's ID: jerrytli
> Add Jerry's id

- 2021_Roster.csv
I think I am doing this right?
> Added gh username for Allyson Weir

- 2021_Roster.csv
> Added Corinne Matthews' name to list of github usernames

- 2021_Roster.csv
> Venkatesh, Rasika username addition

- 2021_Roster.csv
> added my dumb github username

- 2021_Roster.csv
Exactly What It Says On The Tin
> added username to roster

- 2022_Roster.csv
I've added my GitHub username to the file.
> Added my GitHub username to the file

- 2023_Roster.csv
Added Dirks, Noah GitHub Username.
> Change Dirks, Noah Username

- 2023_Roster.csv
To update roster for GitHub usernames
> Added SydWong as username to roster

- 2023_Roster.csv
added username wbclaflin following my name in the 2023_Roster.csv file.
> Added username to Roster file

- 2023_Roster.csv
fixed problems from last pull request
> added name and added readme

- 2023_Roster.csv
Hello! Here is the new roster with my updated username
> updated my username
